# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WnmlM0QYinJ40UF2C8RSeobOqVWQaFO8
"""


import numpy as np
import pandas as pd
import streamlit as st
import datetime



data = pd.read_csv("/content/50_Startups.csv")
data.head
data=pd.DataFrame(data)
data.head

st.dataframe(data)

st.table(data)

